
width = 11
height = 10


words = ['NOOGLER', 'MAKERS', 'PLAY', 'MICRO-KITCHEN', 'SERGEY', 'SOLDER', 'ADS', 'LARRY',
'LEARN', 'CUT', 'ARDUINO', 'ENGRAVE', 'NAIL', 'OPPORTUNITY', 'MOMA', 'MAKE', 'HAMMER', 'MISS', 
'TRY', 'CLOUD', 'SEARCH', 'DO', 'LEARNING', 'THING', 'LASER', 'FAIL', 'ANDROID', 'SPACE', 'PRINT', 
'CAFE', 'TGIF', 'CHROMEDINO', 'PHOTOS', 'HELLO', 'MEMEGEN', 'TENSORFLOW', 'YOUTUBE', 'MAKE', 
'PAR-RDL', 'MAPS', 'DRIVE', 'RESISTOR', 'RESPECT', 'MACHINE', 'RIGHT', 'GOOGLE', 'USER', 
'CREATE', 'SEW', 'DOGFOOD']

